### ISSUE TITLE
transparent backgrond

### ISSUE THREAD

**Issue by Macka323** [st-one-io/node-red-contrib-ui-media#23]
Hi, is there a way to change the background of the media, ex. if i put image in the node, when its displayed on the dashboard there is like white border, and it will be great if you can change the color to be transparent or to remove it. If its easier you can tell me what files to modify.

**Comment by machadotiago** [comment]
sorry, that is not purpose of this node. such a functionality would require a brand new node.

**Comment by Macka323** [comment]
is there a way to change it manually or remove it
![Screenshot 2021-01-12 022159](https://user-images.githubusercontent.com/75259519/104323187-2c74de80-54e6-11eb-942d-7b1a395942aa.png)

**Comment by machadotiago** [comment]
Unfortunately not. For such a change you will need to use the Dashboard Template  and write the HTML manually.
